POST http://localhost:8107/racoon/validation
Content-Type: application/json

{
  "email": "b@b.pl2344"
}

###

POST http://localhost:8107/racoon/validation/async
Content-Type: application/json

{
  "emails": [
    "a@a.pl",
    "info@magicline.de"
  ]
}

###