server:
  port: 8107

management:
  metrics.export.prometheus.enabled: true
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include: "metrics,prometheus"

spring:
  application:
    name: bouncing-racoon
  main:
    banner-mode: "off"
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host:localhost}:${db.port:65432}/${db.name:racoon}?ssl=${db.ssl:false}&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: ${db.user:racoon}
    password: ${db.password:changeme}
  flyway:
    table: schema_version
    locations: classpath:db/migrations
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: "validate"
  rabbitmq:
    host:         ${rabbitmq.host:localhost}
    username:     ${rabbitmq.username:testuser}
    password:     ${rabbitmq.password:pass}
    virtual-host: ${rabbitmq.vhost:/magicline}
    dynamic:      true

app:
  provider:
    uris:
#      sync: "http://localhost:8107/racoon/mock"
#      async: "http://localhost:8107/racoon/mock"
      sync: "https://api.email-validator.net"
      async: "https://bulk.email-validator.net"
      results: "https://www.email-validator.net"
    apiKey: "ev-7791b803c271ab303acfa5029b1847e1"
    notifyURL: http://localhost:8107/racoon/tasks/callbacks
    notifyEmail:
    validationMode: EXPRESS
    retries:
      maxAttempts: 3
      initialIntervalSec: 10
  task:
    status:
      batch: 100

  job.delay:
      # https://www.logicbig.com/how-to/code-snippets/jcode-java-8-date-time-api-duration-parse.html
      metrics: "PT1H"
      cleanup: "PT24H"

logging:
  config:
    "classpath:log4j2.xml"
  level:
    de.magicline.racoon.domain.provider.RTEVValidationClient: ${logging.feign.level:DEBUG}