server:
  port: 8107

spring:
  application:
    name: bouncing-racoon
  main:
    banner-mode: "off"
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host:localhost}:${db.port:65432}/${db.name:racoon}?ssl=${db.ssl:false}&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: ${db.user:racoon}
    password: ${db.password:changeme}
  flyway:
    table: schema_version
    locations: classpath:db/migrations
    baseline-on-migrate: true
  rabbitmq:
    host:         ${rabbitmq.host:localhost}
    username:     ${rabbitmq.username:testuser}
    password:     ${rabbitmq.password:pass}
    virtual-host: ${rabbitmq.vhost:/magicline}
    dynamic:      true

app:
  rtev:
    apiKey: "ev-7791b803c271ab303acfa5029b1847e1"
    notifyURL: http://localhost:8107/racoon/tasks/callbacks
    retry:
      maxAttempts: 3
      initialIntervalSec: 10

  task:
    status:
      batch: 100

logging:
  config:
    "classpath:log4j2.xml"