version: "3"

services:
  postgres:
    image: postgres:10.7-alpine
    ports:
      - "65432:5432"
    restart: always
    volumes:
          - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
  rabbitmq:
    image: "rabbitmq:3.6.12"
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: testuser
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_VHOST: /magicline
  maven:
    image: 221489699002.dkr.ecr.eu-central-1.amazonaws.com/sportalliance/maven-builder:jdk-11
    environment:
        - MAVEN_USER=tc_magicline
        - MAVEN_PASSWORD=sSWqHT7nrBqscWtH
        - DB_HOST=postgres
        - DB_PORT=5432
        - DB_NAME=racoon
        - DB_USER=racoon
        - DB_PASSWORD=changeme
        - DB_SSL=false
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_VHOST=/magicline
        - RABBITMQ_USERNAME=testuser
        - RABBITMQ_PASSWORD=pass
    links:
        - postgres
        - rabbitmq
    volumes:
        - "./../:/app"
        - "~/.m2/repository:/root/.m2/repository"
        - "~/.docker:/root/.docker"
    working_dir: /app
    command: ["mvn", "-e","-B", "clean", "verify","-Dml.log.dir=/tmp" ]
