@startuml

actor client
actor RTEV

package domain {
    [provider]
    [task]
    [status]
}

domain .. [config]
[job] .. [config]
[job]  --> task: clean up

client -> [api]
[api] -> [provider] : validate emails
[provider] --> RTEV: use
RTEV -> [task] : create|complete
[task] -> [status] : publish
[status] -> client : notify

@enduml