@startuml
participant "ml-backend" as MLB
participant "ml-bouncing-racoon" as BR
actor "email-validator.net" as RTEV
boundary "ml-external-api" as API

MLB -> BR : validate e-mails
BR -> RTEV : POST api/verify
RTEV -> API : callback
API -> BR : taskId
BR -> RTEV : POST /download.html
BR -> BR : taskResult
BR -> MLB : statusMessage
...
BR -> MLB : statusMessage
@enduml