---
host: bouncing-racoon.dev.magicline.com
image: docker.pkg.github.com/sportalliance/ml-bouncing-racoon/ml-bouncing-racoon
memoryRequest: 900Mi
memoryLimit: 900Mi
servicePort: 8122
replicas: 1
healthcheck:
  path: /ping
metrics:
  path: /actuator/prometheus
imagePullSecrets:
  - name: docker-github-image-pull-secret
sendConsoleLogsToGraylog: false
env:
- name: SPRING_PROFILES_ACTIVE
  value: dev
- name: ML_APP_NAME
  value: ml-bouncing-racoon-dev
- name: GRAYLOG_HOST
  value: graylog-input.logging
- name: DB_HOST
  value: ml-db-bouncingracoon.cwwu8vfqevzy.eu-west-1.rds.amazonaws.com
- name: DB_PORT
  value: 5432
- name: DB_NAME
  value: racoon
- name: DB_SSL
  value: true
- name: DB_USER
  valueFromSecret:
    name: database
    key: user
- name: DB_PASSWORD
  valueFromSecret:
    name: database
    key: password
- name: RABBITMQ_HOST
  value: crisp-leopard.rmq.cloudamqp.com
- name: RABBITMQ_VHOST
  value: magicline-dev
- name: RABBITMQ_USERNAME
  valueFromSecret:
     name: rabbitmq
     key: username
- name: RABBITMQ_PASSWORD
  valueFromSecret:
     name: rabbitmq
     key: password
- name: LOGGING_FEIGN_LEVEL
  value: INFO
- name: APP_PROVIDER_APIKEY
  valueFromSecret:
    name: provider
    key: token